import { Router } from "express";
import { createCrudController } from "../controllers/crudController.js";
import { BouncedCheck } from "../models/bouncedChecks.model.js";
import { auth } from "../middleware/auth.middleware.js";
const { getAll, getOne, create, update, remove } = createCrudController(BouncedCheck);
export const bouncedChecksRouter = Router();
bouncedChecksRouter.get("/", auth, getAll);
bouncedChecksRouter.get("/:id", auth, getOne);
bouncedChecksRouter.post("/", auth, create);
bouncedChecksRouter.put("/:id", auth, update);
bouncedChecksRouter.delete("/:id", auth, remove);
