import { Router } from "express";
import { createCrudController } from "../controllers/crudController.js";
import { Event } from "../models/event.model.js";
import { auth } from "../middleware/auth.middleware.js";
const { getAll, getOne, create, update, remove } = createCrudController(Event);
export const eventsRouter = Router();
eventsRouter.get("/", auth, getAll);
eventsRouter.get("/:id", auth, getOne);
eventsRouter.post("/", auth, create);
eventsRouter.put("/:id", auth, update);
eventsRouter.delete("/:id", auth, remove);
