import { Router } from "express";
import { createCrudController } from "../controllers/crudController.js";
import { Provider } from "../models/provider.model.js";
import { auth } from "../middleware/auth.middleware.js";
const { getAll, getOne, create, update, remove } = createCrudController(Provider);
export const providersRouter = Router();
providersRouter.get("/", auth, getAll);
providersRouter.get("/:id", auth, getOne);
providersRouter.post("/", auth, create);
providersRouter.put("/:id", auth, update);
providersRouter.delete("/:id", auth, remove);
